language: node_js
node_js:
    - '7'
cache:
    directories:
        - 'node_modules'
deploy:
    provider: npm
    email: 'stephenwpoole@gmail.com'
    api_key: '801dd0e9-e824-4a3d-b850-0c9930d0cae1'
    on:
        tags: true
        branch: master
script:
    - npm install codecov -g
    - npm install
    - npm test
    - npm start
after_success:
    - nyc report --reporter=json > coverage/coverage.json && codecov --token=7dfa0e8a-8bc7-4e18-83a9-cd081d6b54c7
